name: Windows ROS Chocolatey CI
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC 
  - cron:  '0 3 * * *'
  
  
jobs:
  build:
    name: 'Windows ROS Chocolatey CI'
    runs-on: windows-latest
    strategy:
      matrix:
        project_tags: [Stable, Unstable]

    steps:
    - uses: actions/checkout@master
        
    # Print environment variables to simplify development and debugging
    - name: Environment Variables
      shell: bash
      run: env
        
    # ============
    # DEPENDENCIES
    # ============
        
    - name: Dependencies
      shell: cmd
      run: |
        choco sources add -n=roswin -s https://roswin.azurewebsites.net/api/v2/ --priority 1
        choco upgrade ros-melodic-desktop ros-vcpkg -y
        call "C:\opt\ros\melodic\x64\setup.bat"
        git clone https://github.com/robotology-dependencies/robotology-vcpkg-binary-ports C:/robotology-vcpkg-binary-ports
        vcpkg.exe --triplet x64-windows --overlay-ports=C:/robotology-vcpkg-binary-ports install ace gsl ode libxml2 ipopt-binary
        
    # ===================
    # CMAKE-BASED PROJECT
    # ===================

    - name: Configure & Build 
      shell: cmd
      run: |
        call "C:\opt\ros\melodic\x64\setup.bat"
        # Workaround for https://github.com/ms-iot/ROSOnWindows/issues/164
        set PATH=%PATH%;c:\opt\vcpkg\installed\x64-windows\bin
        mkdir build
        cd build    
        cmake -A x64  -DROBOTOLOGY_USES_GAZEBO:BOOL=ON -DROBOTOLOGY_USES_OCTAVE:BOOL=OFF -DROBOTOLOGY_USES_PYTHON:BOOL=OFF -DROBOTOLOGY_ENABLE_ROBOT_TESTING:BOOL=ON -DROBOTOLOGY_ENABLE_DYNAMICS:BOOL=OFF -DROBOTOLOGY_ENABLE_HUMAN_DYNAMICS:BOOL=ON -DROBOTOLOGY_ENABLE_ICUB_HEAD:BOOL=ON -DNON_INTERACTIVE_BUILD:BOOL=TRUE -DCMAKE_BUILD_TYPE=Release..
        cmake --build . --config Release
        
        
